# Generated by Django 5.0.2 on 2024-05-01 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Breed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breed_of_dog', models.CharField(max_length=200)),
                ('discription', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TrainingType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_training', models.CharField(max_length=200)),
                ('discription', models.TextField()),
                ('duration', models.PositiveSmallIntegerField()),
                ('cost', models.PositiveBigIntegerField()),
            ],
        ),
    ]
