# Generated by Django 5.0.2 on 2024-05-06 08:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication_app', '0003_alter_customuser_options_customuser_date_joined_and_more'),
        ('shared_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.PositiveBigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PetDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pet_name', models.CharField(max_length=50)),
                ('pet_behavior', models.CharField(max_length=200)),
                ('pet_age', models.PositiveSmallIntegerField()),
                ('meal_timing', models.CharField(max_length=2000)),
                ('discription', models.TextField()),
                ('breed_of_doge', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='shared_app.breed')),
                ('type_of_training', models.ManyToManyField(to='shared_app.trainingtype')),
            ],
        ),
    ]
