# Generated by Django 5.0.4 on 2024-05-07 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication_app', '0007_userandpetdetails_remove_petdetails_breed_of_doge_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userandpetdetails',
            old_name='breed_of_doge',
            new_name='breed_of_dog',
        ),
    ]
