# Generated by Django 5.0.4 on 2024-05-07 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication_app', '0008_rename_breed_of_doge_userandpetdetails_breed_of_dog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userandpetdetails',
            name='pet_age',
            field=models.CharField(max_length=100),
        ),
    ]
