# Generated by Django 5.0.4 on 2024-05-07 05:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication_app', '0009_alter_userandpetdetails_pet_age'),
        ('shared_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userandpetdetails',
            name='type_of_training',
        ),
        migrations.AddField(
            model_name='userandpetdetails',
            name='type_of_training',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='shared_app.trainingtype'),
            preserve_default=False,
        ),
    ]
