# Generated by Django 5.0.4 on 2024-05-16 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication_app', '0012_petandtrainermapping'),
    ]

    operations = [
        migrations.AddField(
            model_name='userandpetdetails',
            name='is_training_complete',
            field=models.BooleanField(default=False),
        ),
    ]
